export const FALLBACK_EXPERIENCE = [
  {
    _id: "exp_1",
    company: "Siellum Global Labs Pvt. Ltd.",
    title: "Software Developer Intern",
    startDate: "May 2026",
    endDate: "Jun 2026",
    sortIndex: 1,
    hide: false,
  },
  {
    _id: "exp_2",
    company: "AICTE & Salesforce",
    title: "Salesforce Virtual Intern",
    startDate: "May 2025",
    endDate: "Jul 2025",
    sortIndex: 2,
    hide: false,
  },
];

export const FALLBACK_PROJECTS = [
  {
    _id: "proj_neighbourhub",
    name: "NeighbourHub",
    year: 2026,
    liveUrl: "https://hyperlocal-community-platform.vercel.app/",
    sourceCode: "https://github.com/VinayJoshi16/NeighbourHub",
    description: "NeighbourHub is a real-time hyperlocal community platform that brings neighborhoods closer together. It enables live group chats, polls, notice boards, and geolocation-based emergency alerts to keep local communities safe and informed.",
    features: [
      "Architected real-time communication using Socket.IO / WebSockets for live group chats and community polls.",
      "Implemented a secure auth/push pipeline with JWT, bcryptjs, multi-factor OTP via Nodemailer, and Web Push VAPID keys.",
      "Configured Helmet headers (CORP/COEP) for secure cross-origin attachment streaming.",
      "Optimized reliability via Express Reverse Proxy Trust and load-balancer-aware rate limiters to handle peak concurrent traffic.",
    ],
    techStack: ["React.js", "Redux Toolkit", "Node.js", "Express.js", "Socket.IO", "PostgreSQL", "Gemini AI", "Web Push", "Nodemailer", "Vercel", "Render", "Neon"],
    thumbnail: "/projects/neighbourhub.png",
    sortIndex: 1,
    slug: "neighbourhub",
    hide: false,
  },
  {
    _id: "proj_adaptive_learning",
    name: "Adaptive Learning Platform",
    year: 2026,
    liveUrl: "https://adaptive-learning-path-50.vercel.app/",
    sourceCode: "https://github.com/VinayJoshi16/Adaptive-Learning-Platform",
    description: "A state-of-the-art adaptive learning platform leveraging client-side Machine Learning. The platform analyzes student engagement in real-time and dynamically structures learning paths based on comprehension metrics.",
    features: [
      "Engineered an adaptive learning algorithm generating custom education paths based on historical progress.",
      "Integrated TensorFlow.js for local client-side ML inference, reducing server load and response latency.",
      "Built real-time student engagement monitoring leveraging facial expression analysis via MediaPipe.",
      "Designed and implemented 15+ REST API endpoints with JWT authentication, request validation, and query analytics.",
      "Modelled flexible and scalable schema in MongoDB Atlas for fast course progression lookup.",
    ],
    techStack: ["React.js", "TypeScript", "Node.js", "Express.js", "MongoDB Atlas", "TensorFlow.js", "MediaPipe"],
    thumbnail: "/projects/adaptive_learning.png",
    sortIndex: 2,
    slug: "adaptive-learning-platform",
    hide: false,
  },
  {
    _id: "proj_bike_rental",
    name: "Bike Rental System",
    year: 2025,
    liveUrl: "https://ip-address-tracker-yihc.vercel.app/",
    sourceCode: "https://github.com/VinayJoshi16/Bike-Rental-System",
    description: "A comprehensive booking and rental management system. The platform streamlines vehicle availability, handles reservations under high concurrent load, and provides administrators with real-time insights.",
    features: [
      "Developed high-throughput RESTful APIs for booking, authentication, and inventory, successfully handling 100+ concurrent operations.",
      "Reduced vehicle booking conflicts by 30% via transactional lock mechanisms in MongoDB.",
      "Created role-based dashboards featuring advanced grid filtering, real-time vehicle tracking, and analytics.",
    ],
    techStack: ["React.js", "TypeScript", "Vite", "Tailwind CSS", "Node.js", "Express.js", "MongoDB", "JWT", "REST APIs"],
    thumbnail: "/projects/bike_rental.png",
    sortIndex: 3,
    slug: "bike-rental-system",
    hide: false,
  },
  {
    _id: "proj_page_replacement",
    name: "Page Replacement Algorithm Visualizer",
    year: 2024,
    liveUrl: "https://page-replacement-algorithm-visualiz.vercel.app/",
    sourceCode: "https://github.com/VinayJoshi16/Page-Replacement-Algorithm-Visualizer",
    description: "An interactive educational tool that visualizes operating system page replacement algorithms like FIFO, LRU, and Optimal. It allows users to simulate memory management, step through algorithmic execution, and compare performance metrics visually.",
    features: [
      "Built an interactive simulation engine to visually step through FIFO, LRU, and Optimal algorithms.",
      "Implemented dynamic charts and memory state blocks to trace page faults and hits in real-time.",
      "Designed a clean, responsive data-oriented dashboard with Tailwind CSS and React hooks.",
    ],
    techStack: ["React.js", "Tailwind CSS", "JavaScript", "Vercel"],
    thumbnail: "/projects/page_replacement.jpg",
    sortIndex: 4,
    slug: "page-replacement-algorithm-visualizer",
    hide: false,
  },
];

export const FALLBACK_STACK = [
  {
    type: "frontend",
    items: [
      { _id: "st_react", name: "React.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", type: "frontend", sortIndex: 1, hide: false },
      { _id: "st_next", name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", type: "frontend", sortIndex: 2, hide: false },
      { _id: "st_ts", name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", type: "frontend", sortIndex: 3, hide: false },
      { _id: "st_js", name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", type: "frontend", sortIndex: 4, hide: false },
      { _id: "st_html", name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg", type: "frontend", sortIndex: 5, hide: false },
      { _id: "st_css", name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg", type: "frontend", sortIndex: 6, hide: false },
      { _id: "st_tailwind", name: "Tailwind CSS", icon: "https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-original.svg", type: "frontend", sortIndex: 7, hide: false },
      { _id: "st_redux", name: "Redux Toolkit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg", type: "frontend", sortIndex: 8, hide: false },
      { _id: "st_vite", name: "Vite", icon: "https://raw.githubusercontent.com/devicons/devicon/master/icons/vite/vite-original.svg", type: "frontend", sortIndex: 9, hide: false },
    ],
  },
  {
    type: "backend",
    items: [
      { _id: "st_node", name: "Node.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", type: "backend", sortIndex: 1, hide: false },
      { _id: "st_express", name: "Express.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg", type: "backend", sortIndex: 2, hide: false },
      { _id: "st_pg", name: "PostgreSQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", type: "backend", sortIndex: 3, hide: false },
      { _id: "st_mongodb", name: "MongoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg", type: "backend", sortIndex: 4, hide: false },
      { _id: "st_mysql", name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg", type: "backend", sortIndex: 5, hide: false },
      { _id: "st_firebase", name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-original.svg", type: "backend", sortIndex: 6, hide: false },
      { _id: "st_socketio", name: "Socket.IO", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg", type: "backend", sortIndex: 7, hide: false },
    ],
  },
  {
    type: "tools",
    items: [
      { _id: "st_aws", name: "AWS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg", type: "tools", sortIndex: 1, hide: false },
      { _id: "st_docker", name: "Docker", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", type: "tools", sortIndex: 2, hide: false },
      { _id: "st_redis", name: "Redis", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg", type: "tools", sortIndex: 3, hide: false },
      { _id: "st_git", name: "Git", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg", type: "tools", sortIndex: 4, hide: false },
      { _id: "st_linux", name: "Linux", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg", type: "tools", sortIndex: 5, hide: false },
      { _id: "st_vscode", name: "VS Code", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg", type: "tools", sortIndex: 6, hide: false },
      { _id: "st_postman", name: "Postman", icon: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postman/postman-original.svg", type: "tools", sortIndex: 7, hide: false },
    ],
  },
  {
    type: "studying",
    items: [
      { _id: "st_tensorflow", name: "TensorFlow.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg", type: "studying", sortIndex: 1, hide: false },
      { _id: "st_gemini", name: "Gemini AI", icon: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002d472bce31c74.svg", type: "studying", sortIndex: 2, hide: false },
      { _id: "st_cloud_ai", name: "Cloud AI", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg", type: "studying", sortIndex: 3, hide: false },
      { _id: "st_cplusplus", name: "C++", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg", type: "studying", sortIndex: 4, hide: false },
      { _id: "st_java", name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", type: "studying", sortIndex: 5, hide: false },
    ],
  },
];
